# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 1050)
        self.Pulse = QtWidgets.QGraphicsView(MainWindow)
        self.Pulse.setGeometry(QtCore.QRect(1180, 610, 471, 411))
        self.Pulse.setObjectName("Pulse")
        self.Eeg = QtWidgets.QGraphicsView(MainWindow)
        self.Eeg.setGeometry(QtCore.QRect(680, 610, 471, 411))
        self.Eeg.setObjectName("Eeg")
        self.Cardio = QtWidgets.QGraphicsView(MainWindow)
        self.Cardio.setGeometry(QtCore.QRect(680, 90, 971, 461))
        self.Cardio.setObjectName("Cardio")
        self.verticalScrollBar = QtWidgets.QScrollBar(MainWindow)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1660, 0, 20, 1051))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(680, 560, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 560, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(840, 560, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(690, 590, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(1180, 590, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(680, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(920, 560, 401, 20))
        self.label_4.setObjectName("label_4")
        self.ChooseFile = QtWidgets.QLineEdit(MainWindow)
        self.ChooseFile.setGeometry(QtCore.QRect(270, 70, 171, 20))
        self.ChooseFile.setObjectName("ChooseFile")
        self.File_button = QtWidgets.QPushButton(MainWindow)
        self.File_button.setGeometry(QtCore.QRect(450, 70, 75, 23))
        self.File_button.setObjectName("File_button")
        self.treeView = QtWidgets.QTreeView(MainWindow)
        self.treeView.setGeometry(QtCore.QRect(10, 100, 391, 941))
        self.treeView.setObjectName("treeView")
        self.ChooseDirectory = QtWidgets.QLineEdit(MainWindow)
        self.ChooseDirectory.setGeometry(QtCore.QRect(10, 70, 171, 20))
        self.ChooseDirectory.setObjectName("ChooseDirectory")
        self.Directory_button = QtWidgets.QPushButton(MainWindow)
        self.Directory_button.setGeometry(QtCore.QRect(190, 70, 75, 23))
        self.Directory_button.setObjectName("Directory_button")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 261, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(270, 40, 261, 20))
        self.label_6.setObjectName("label_6")
        self.Shapka = QtWidgets.QLabel(MainWindow)
        self.Shapka.setGeometry(QtCore.QRect(670, 50, 841, 101))
        self.Shapka.setText("")
        self.Shapka.setObjectName("Shapka")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.pushButton.setText(_translate("MainWindow", "Фильтр1"))
        self.pushButton_2.setText(_translate("MainWindow", "Фильтр2"))
        self.pushButton_3.setText(_translate("MainWindow", "Фильтр3"))
        self.label.setText(_translate("MainWindow", "ЭЭГ"))
        self.label_2.setText(_translate("MainWindow", "Пульс"))
        self.label_3.setText(_translate("MainWindow", "ЭКГ"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.File_button.setText(_translate("MainWindow", "PushButton"))
        self.Directory_button.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "Загрузка директории"))
        self.label_6.setText(_translate("MainWindow", "Загрузка файла"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
