# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 1050)
        self.Pulse = QtWidgets.QGraphicsView(MainWindow)
        self.Pulse.setGeometry(QtCore.QRect(1180, 610, 471, 411))
        self.Pulse.setObjectName("Pulse")
        self.Eeg = QtWidgets.QGraphicsView(MainWindow)
        self.Eeg.setGeometry(QtCore.QRect(680, 610, 471, 411))
        self.Eeg.setObjectName("Eeg")
        self.Cardio = QtWidgets.QGraphicsView(MainWindow)
        self.Cardio.setGeometry(QtCore.QRect(680, 90, 971, 461))
        self.Cardio.setObjectName("Cardio")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(690, 590, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(1180, 590, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(680, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(680, 560, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ChooseFile = QtWidgets.QLineEdit(MainWindow)
        self.ChooseFile.setGeometry(QtCore.QRect(10, 80, 171, 20))
        self.ChooseFile.setObjectName("ChooseFile")
        self.File_button = QtWidgets.QPushButton(MainWindow)
        self.File_button.setGeometry(QtCore.QRect(190, 80, 101, 23))
        self.File_button.setObjectName("File_button")
        self.treeView = QtWidgets.QTreeView(MainWindow)
        self.treeView.setGeometry(QtCore.QRect(10, 120, 361, 921))
        self.treeView.setObjectName("treeView")
        self.ChooseDirectory = QtWidgets.QLineEdit(MainWindow)
        self.ChooseDirectory.setGeometry(QtCore.QRect(10, 40, 171, 20))
        self.ChooseDirectory.setObjectName("ChooseDirectory")
        self.Directory_button = QtWidgets.QPushButton(MainWindow)
        self.Directory_button.setGeometry(QtCore.QRect(190, 40, 101, 23))
        self.Directory_button.setObjectName("Directory_button")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Shapka = QtWidgets.QLabel(MainWindow)
        self.Shapka.setGeometry(QtCore.QRect(380, 90, 291, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Shapka.setFont(font)
        self.Shapka.setText("")
        self.Shapka.setObjectName("Shapka")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Обработка ЭКГ"))
        self.label.setText(_translate("MainWindow", "ЭЭГ"))
        self.label_2.setText(_translate("MainWindow", "Пульс"))
        self.label_3.setText(_translate("MainWindow", "ЭКГ"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.File_button.setText(_translate("MainWindow", "PushButton"))
        self.Directory_button.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "Загрузка директории"))
        self.label_6.setText(_translate("MainWindow", "Загрузка файла"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
